#!/usr/bin/env python3
#
# Regenerates Sources/MeterUsage/Views/CodexMark.swift from the parametric
# petal definition below.
#
# The OpenAI/Codex mark is a 6-petal blossom: each petal is a thin stem flaring
# into a rounded blade, repeated every 60 degrees. The proportions here were
# measured against the official mark so the small 13pt menu-bar glyph reads as
# the same object. Run this script only when the shape itself changes; the
# committed Swift file is the source of truth for builds.
#
#   python3 Scripts/trace-codex.py
#
import math
from pathlib import Path

# Petal profile as (radius, half-angle) pairs from the stem base to the tip.
# Radius is measured from the glyph centre on a 0..0.5 scale; half-angle is in
# radians from the petal axis.
PETAL = [
    (0.095, 0.050), (0.150, 0.055), (0.205, 0.060), (0.255, 0.070),
    (0.300, 0.095), (0.335, 0.140), (0.365, 0.190), (0.390, 0.225),
    (0.410, 0.235), (0.428, 0.215), (0.440, 0.175), (0.447, 0.120),
    (0.451, 0.055), (0.452, 0.000),
]

# A 6-petal blossom is symmetric about the centre; each petal spans 60 degrees.
ROTATIONS = 6

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "Sources" / "MeterUsage" / "Views" / "CodexMark.swift"


def petal_points():
    points = []
    for r, a in PETAL:
        points.append((r * math.sin(a), -r * math.cos(a)))
    for r, a in reversed(PETAL[:-1]):
        points.append((-r * math.sin(a), -r * math.cos(a)))
    return points


def rotate(point, angle):
    x, y = point
    c, s = math.cos(angle), math.sin(angle)
    return (x * c - y * s, x * s + y * c)


def to_box(point):
    x = (point[0] / 0.5 + 1) / 2
    y = (point[1] / 0.5 + 1) / 2
    return (x, y)


def catmull_rom_segments(chain):
    n = len(chain)
    for i in range(n - 1):
        p0 = chain[max(i - 1, 0)]
        p1 = chain[i]
        p2 = chain[i + 1]
        p3 = chain[min(i + 2, n - 1)]
        c1 = (p1[0] + (p2[0] - p0[0]) / 6, p1[1] + (p2[1] - p0[1]) / 6)
        c2 = (p2[0] - (p3[0] - p1[0]) / 6, p2[1] - (p3[1] - p1[1]) / 6)
        yield p2, c1, c2


def build_swift():
    lines = [
        "import SwiftUI",
        "",
        "// The OpenAI/Codex mark, drawn as a parametric 6-petal blossom so the menu-bar",
        "// glyph can be tinted like any other template shape. The petal proportions were",
        "// measured against the official mark and are regenerated by",
        "// `Scripts/trace-codex.py`; do not hand-edit the curves below.",
        "//",
        "// Each petal is its own closed subpath: a thin stem flaring into a rounded",
        "// blade that points outward, repeated every 60 degrees.",
        "struct CodexMark: Shape {",
        "    func path(in rect: CGRect) -> Path {",
        "        var p = Path()",
        "        func pt(_ x: CGFloat, _ y: CGFloat) -> CGPoint {",
        "            CGPoint(x: rect.minX + rect.width * x, y: rect.minY + rect.height * y)",
        "        }",
    ]
    for k in range(ROTATIONS):
        angle = k * math.pi / 3
        chain = [to_box(rotate(p, angle)) for p in petal_points()]
        x0, y0 = chain[0]
        lines.append(f"        p.move(to: pt({x0:.4f}, {y0:.4f}))")
        for p2, c1, c2 in catmull_rom_segments(chain):
            lines.append(
                f"        p.addCurve(to: pt({p2[0]:.4f}, {p2[1]:.4f}), "
                f"control1: pt({c1[0]:.4f}, {c1[1]:.4f}), "
                f"control2: pt({c2[0]:.4f}, {c2[1]:.4f}))"
            )
        lines.append("        p.closeSubpath()")
    lines.extend([
        "        return p",
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


def main():
    generated = build_swift()
    existing = OUTPUT.read_text() if OUTPUT.exists() else None
    if existing == generated:
        print("CodexMark.swift is already up to date")
        return
    OUTPUT.write_text(generated)
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()